### ISSUE TITLE
Moving all data from an event deletes all data for those events if data already exists in other event. 

### ISSUE THREAD

**Issue by biggeeves** [ctsit/move_data_to_other_event#5]
Steps to reproduce
1) Select Record #1 Record Home Page
2) Click on the red truck under 2nd event
3) Click on "Migrate Event Data".

All data is erased from the Second event.

Suggestion: Don't delete data until the data has been moved.  Allow users to select "Keep Existing Data" to override the delete data option.  This would be especially good during development and test and also for new users of the module to confirm the data has actually moved correctly. 

XML file is in a ZIP file.   It contains all instruments, 1 record, and the events.  Create a new project from the file, add the module and follow the steps above to reproduce the bug. 

Tested on REDCap 9.2.5
[TEST_2019-10-16_1611.REDCap.xml.zip](https://github.com/ctsit/move_data_to_other_event/files/3736729/TEST_2019-10-16_1611.REDCap.xml.zip)

**Comment by ChemiKyle** [comment]
@biggeeves thank you for the project XML.

Since the dropdown does not populate if there are not valid target events, users are not expected to click the "Migrate Event Data" button at all. I'll treat this issue as a combination of 2 suggestions from REDCap community I'm already working on:  
1. Altering the UI to alert users when there are no valid targets for migration rather than simply providing an empty dropdown. It may be a good idea to disable the "Migrate Data" button in case someone decides to click it anyway.
2. Provide the option to retain data in the source after migrating to target instead of deleting it.

**Comment by pbchase** [comment]
closed by PR #6
